[tool.black]
exclude = '''
/(
    \.git
  | build
  | dist
)/
'''
include = '\.pyi?$'
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
combine_as_imports = true
from_first = true
line_length = 88
profile = "black"
